Repository instructlab/ui, pull requests merged in 2024-12, with the labels that each got.

#383 Fix local git submissions by casting to KnowledgeYamlData
  src/app/api/local/pr/knowledge/route.ts
Labels: bug

#378 remove CI_AUTOMATION workflow errors by checking skip
  .github/workflows/pr-images.yml
Labels: bug, CI/CD, ready-for-review

#407 apply our license
  LICENSE
Labels: bug, tech debt, ready-for-review

#409 updating umami argocd app to use prod overlay and cluster
  argocd/overlays/applicaitons/umami.yaml
Labels: bug, deployment, ready-for-review

#419 [FIX] QA publish pathservice job now updates its own image
  .github/workflows/pr-images.yml
Labels: bug, CI/CD

#427 fixing make ui-image target and containerized UI builds
  .dockerignore
  next-env.d.ts
  package-lock.json
  package.json
  src/Containerfile
Labels: bug, tech debt, ready-for-review

#430 feature request template
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: tech debt

#432 issue template not getting picked up because of naming conventions
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: bug, ready-for-review

#428 Makefile Madness: Monolithic to Makefile subdirs migration
  Makefile
  Makefiles/containers-base/Makefile
  Makefiles/deployment/common/Makefile
  Makefiles/deployment/kind/Makefile
  Makefiles/deployment/openshift/prod/Makefile
  Makefiles/deployment/openshift/qa/Makefile
  Makefiles/devcontainer/Makefile
  Makefiles/linting/Makefile
  Makefiles/local/Makefile
  Makefiles/podman-compose/Makefile
Labels: tech debt, ready-for-review

#435 Fix view code modal from PF6 breakage
  src/components/YamlCodeModal/index.tsx
Labels: bug

#375 implementing healthcheck sidecar and probe
  .env.github.example
  .github/workflows/pr-healthcheck-sidecar-image.yml
  .gitignore
  Makefiles/containers-base/Makefile
  Makefiles/local/Makefile
  deploy/k8s/base/healthcheck-sidecar/kustomization.yaml
  deploy/k8s/base/healthcheck-sidecar/service.yaml
  deploy/k8s/overlays/kind/kustomization.yaml
  deploy/k8s/overlays/openshift/common/kustomization.yaml
  deploy/k8s/overlays/openshift/prod/kustomization.yaml
  deploy/k8s/overlays/openshift/qa/kustomization.yaml
  docs/healthcheck_sidecar.md
  healthcheck-sidecar/Containerfile
  healthcheck-sidecar/requirements.txt
  healthcheck-sidecar/sidecar_script.py
  healthcheck-sidecar/stubbed_model_server.py
  src/Containerfile
  src/healthcheck-probe.sh
Labels: enhancement, release-1.1, deployment, ready-for-review
