Repository instructlab/ui, pull requests merged in 2024-11, with the labels that each got.

#310 adding gap between form elements skill and knowledge
  src/components/Contribute/AuthorInformation.tsx
  src/components/Contribute/Knowledge/AttributionInformation/AttributionInformation.tsx
  src/components/Contribute/Knowledge/DocumentInformation/DocumentInformation.tsx
  src/components/Contribute/Knowledge/KnowledgeInformation/KnowledgeInformation.tsx
  src/components/Contribute/Knowledge/KnowledgeQuestionAnswerPairs/KnowledgeQuestionAnswerPairs.tsx
  src/components/Contribute/Knowledge/index.tsx
  src/components/Contribute/Skill/AttributionInformation/AttributionInformation.tsx
  src/components/Contribute/Skill/SkillsInformation/SkillsInformation.tsx
  src/components/Contribute/Skill/SkillsSeedExample/SkillsSeedExample.tsx
  src/components/PathService/PathService.tsx
Labels: cherry-pick-release-1.0

#338 Bug: use unique keys in in the help dropdown
  src/components/HelpDropdown/HelpDropdown.tsx
Labels: cherry-pick-release-1.0

#366 initial devcontainer implementation
  .devcontainer/Containerfile
  .devcontainer/devcontainer.json
  Makefile
  docs/development.md
Labels: enhancement, UX, tech debt, CI/CD

#376 [FIX] move fast-forward pull before changes to avoid conflict
  .github/workflows/pr-images.yml
  .github/workflows/release-images.yml
Labels: bug, CI/CD

#377 building and publishing devcontainer images in CI
  .github/workflows/devcontainer-image.yml
Labels: CI/CD

#363 refactor image workflows to parallel matrix
  .github/workflows/pr-images.yml
Labels: CI/CD, ready-for-review
