Repository instructlab/ui, pull requests merged in 2025-01, with the labels that each got.

#463 Change the context limit from characters to words
  .env.github.example
  src/components/Contribute/Knowledge/KnowledgeQuestionAnswerPairs/KnowledgeQuestionAnswerPairs.tsx
Labels: bug, cherry-pick-release-1.0

#496 Fix the hydration error on the login page
  src/app/login/page.tsx
Labels: bug

#495 Adds api-server and model eval chat ENVs to native mode example
  .env.native.example
  api-server/README.md
Labels: documentation

#493 PR to test git actions workflow
  README.md
Labels: cherry-pick-release-1.0
